apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: analyzer
  labels:
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      annotations:
        # Use gen2 execution environment for better performance
        run.googleapis.com/execution-environment: gen2
        # Disable CPU throttling to ensure consistent performance during video processing
        run.googleapis.com/cpu-throttling: "false"
        # Use default VPC connector if needed for Cloud SQL or other VPC resources
        # run.googleapis.com/vpc-access-connector: projects/PROJECT_ID/locations/REGION/connectors/CONNECTOR_NAME
        # run.googleapis.com/vpc-access-egress: private-ranges-only
    spec:
      # Only one request at a time per instance (video processing is resource-intensive)
      containerConcurrency: 1
      # 60 minutes timeout for long video processing tasks
      timeoutSeconds: 3600
      # Service account with necessary permissions (Storage, Secret Manager, Firestore)
      serviceAccountName: soccer-analyzer@soccer-analyzer-483917.iam.gserviceaccount.com
      containers:
      - name: analyzer
        # Replace PROJECT_ID with your GCP project ID
        image: gcr.io/soccer-analyzer-483917/soccer-analyzer:latest
        ports:
        - name: http1
          containerPort: 8080
        resources:
          limits:
            # 4 vCPU for parallel processing
            cpu: "4"
            # 16GB RAM for video processing and ML operations
            memory: "16Gi"
        env:
        # Firebase Admin SDK will use Application Default Credentials
        # No need to set GOOGLE_APPLICATION_CREDENTIALS in Cloud Run
        - name: NODE_ENV
          value: "production"
        # GCP Project ID (required for Vertex AI)
        - name: GCP_PROJECT_ID
          value: "soccer-analyzer-483917"
        # GCP Region for Vertex AI (default: us-central1)
        - name: GCP_REGION
          value: "us-central1"
        # Analyzer Tier: 1 = Gemini-first (no YOLO), 2 = Gemini + YOLO
        - name: ANALYZER_TIER
          value: "1"
        # Gemini model to use
        - name: GEMINI_MODEL
          value: "gemini-3-flash-preview"
        # Gemini API location (global required for Gemini 3)
        - name: GEMINI_LOCATION
          value: "global"
        # Context Caching settings (90% cost reduction)
        - name: GEMINI_CONTEXT_CACHE_ENABLED
          value: "true"
        - name: GEMINI_CONTEXT_CACHE_TTL
          value: "3600"
        - name: GEMINI_VIDEO_UPLOAD_FULL
          value: "true"
        # Cloud Storage bucket for video storage (Firebase Storage)
        - name: STORAGE_BUCKET
          value: "soccer-analyzer-483917.firebasestorage.app"
        # Optional: Set FFmpeg log level
        - name: FFMPEG_LOG_LEVEL
          value: "error"
        # Optional: Temporary directory for video processing
        - name: TMPDIR
          value: "/tmp"
        # Startup probe - allow up to 5 minutes for cold start
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
        # Liveness probe
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
  traffic:
  - percent: 100
    latestRevision: true
